### PR TITLE
Upload logo to homepage

### PR DESCRIPTION
**Pull request by lostanlen**
I hold a standard license from this logo:

I made some basic modification to the colors (from red to blue) to avoid any possible confusion with the logo of Keras.

* the segments of the letter K represent the synaptic connections in a neural network
* the waves in the background represents wavelet theory
* the foreground color gray represents a silicon wire
* the different shades of hue in the background represent deep learning

Reach out to me at vincent.lostanlen@nyu.edu if you suggest a modification of this logo

### CODE REVIEW

**Comment by edouardoyallon** [comment]
@lostanlen except if I do not get it, this PR should be in the kymatio/master, not kymatio.github.io/master .

@eickenberg can you confirm?

**Comment by edouardoyallon** [comment]
Please update kymatio/master .

**Comment by eickenberg** [comment]
Hm I am not exactly sure what this PR intends to do in the sense that we now host the webpage here and not the jekyll stub that had a readme + logo as before.

What we are currently hosting here is exactly the docs. So changes to the docs can be pushed here. So the logo should be updated in the docs if anywhere to have an effect

**Comment by lostanlen** [comment]
@eickenberg OK, good to know. I did not want to have the logo uploaded onto the docs because that would make the repository heavier without practical benefit.
Isn't there a way to have a logo on the homepage without having it in the docs?

**Comment by lostanlen** [comment]
I transferred a smaller version of the logo (16 kilobyte) to Edouard off channel

**Pull request closed without merging**
